#ifndef RANDOMBACKGROUNDLIB_GLOBAL_H
#define RANDOMBACKGROUNDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RANDOMBACKGROUNDLIB_LIBRARY)
#  define RANDOMBACKGROUNDLIBSHARED_EXPORT
#else
#  define RANDOMBACKGROUNDLIBSHARED_EXPORT
#endif

#endif // RANDOMBACKGROUNDLIB_GLOBAL_H
